name: eula-aat
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.08.26
- certifi=2017.11.5
- click=6.7
- flask=0.12.2
- intel-openmp=2018.0.0
- itsdangerous=0.24
- jinja2=2.10
- libedit=3.1
- libffi=3.2.1
- markupsafe=1.0
- mkl=2018.0.1
- ncurses=6.0
- numpy=1.14.0
- openssl=1.0.2n
- pip=9.0.1
- python=2.7.14
- readline=7.0
- setuptools=38.4.0
- sqlite=3.21.0
- tk=8.6.7
- werkzeug=0.14.1
- wheel=0.30.0
- zlib=1.2.11
- icu=58.2
- jansson=2.7
- libiconv=1.15
- libxml2=2.9.7
- pcre=8.39
- uwsgi=2.0.16
- xz=5.2.3
- yaml=0.1.7
- pip:
  - aniso8601==2.0.0
  - beautifulsoup4==4.6.0
  - chardet==3.0.4
  - flask-restful==0.3.6
  - idna==2.6
  - jpype1==0.6.2
  - justext==2.2.0
  - lxml==4.1.1
  - nltk==3.2.5
  - pyphen==0.9.4
  - pytz==2017.3
  - readabilitycalculator==0.2.36
  - requests==2.18.4
  - selenium==3.9.0
  - six==1.11.0
  - urllib3==1.22
